### PR TITLE
Tabtabsearch

### PR DESCRIPTION
**Pull request by jmfayard**
Hi Jannes

I am moving home right now, so my schedule is a bit crazy.
But here is my minimum viable product : 

A branch that includes tabtab search inside of tabattack

https://github.com/jmfayard/TabAttack/tree/tabtabsearch

### CODE REVIEW

**Comment by sknebel** [comment]
(just commenting as interested party, I don't have any say in what happens to TabAttack)
I'm curious, what is the motivation for this? Why should this be integrated and not be its own, standalone extension? (I parsed correctly that this is TabTab Search extension in the Chrome Web Store, made by you?)

**Comment by JannesMeyer** [comment]
Hi jmfayard
I'm not exactly sure what the added benefit of merging this over having both as separate extensions is. Could you elaborate a little bit on that?

Over email you told me about your idea to have a history of all exported tabs (stored in IndexedDB or chrome.storage.sync) and that you would like that history to be searchable via an omnibox shortcut. To me that feature doesn't sound so useful, because, in my opinion, the built-in bookmarking feature is much better suited for that.

The scope of TabAttack is specifically to export to the **file sytem** and not to any kind of storage inside the browser, because the data of IndexedDB, for instance, will be lost whenever you re-install the extension, the browser or the OS. Backing up **plain files** is much easier than backing up data inside of extensions.

**Comment by jmfayard** [comment]
Hi Jannes

> I'm not exactly sure what the added benefit of merging this over having both as separate extensions is. 

it was just a first step, which right now absolutely no benefit :)
and in any case I will continue to offer tabtab search as a separate tool for people who wants something simple

I elaborated by email of what I think would be interesting

Your last two paragraphs seem to imply that's not where you aim to go
Well, if that's the case, better to know it now. Fail fast 

   Jean-Michel

**Comment by JannesMeyer** [comment]
Yes, at this point I'm not planning to add that feature. But you are free to adapt TabAttack to your needs, it's GPLv3-licensed. Heck, you can even upload your version to the chrome web store if you want. As long as you don't use the name "TabAttack" I'm totally cool with it.

**Pull request closed without merging**
